### ISSUE TITLE
Why not a plugin or a module?

### ISSUE THREAD

**Issue by sgdc3** [WaterfallMC/Travertine#1]
It would be more simple to keep updated.

**Comment by minecrafter** [comment]
1.7 support requires modifications to the core code to support it.

**Comment by sgdc3** [comment]
ah ok, no way to handle it using packet manipulation?

**Comment by Techcable** [comment]
There _is_ a way to implement it via packet manipulation. Travertine will become obsolete when I finish [SpudCompat](https://github.com/SpudCompat/SpudCompat). (although we may still offer support)

**Comment by sgdc3** [comment]
@Techcable Fine, thank you for the info ;)
