### ISSUE TITLE
 Custom BC names

### ISSUE THREAD

**Issue by Arobcher** [WaterfallMC/Travertine#21]
Excuse me, you can add in Config.yml add
custom_server_name
`custom_server_name: YourBungeeName`

This setting allows you to set a very cool or unique BungeeCord name, as well as he will be displayed in Motd above
For example, version 1.6.4 can not connect to BC server, but he can see
Travertine 1.7.x, 1.8.x ~~~
When you change the CSN
For example: custom_server_name: SuperBungee or more

If you think this is a good suggestion, I hope to use! Thank you
And can also be added within the WaterFall BungeeCord

**Comment by kashike** [comment]
https://github.com/WaterfallMC/Waterfall/issues/96
