### ISSUE TITLE
Merge the latest WaterfallMC commit

### ISSUE THREAD

**Issue by Lmmb74** [WaterfallMC/Travertine#23]
It solves the 1.11 > versions compatibility because of the Title packet.

**Comment by Techcable** [comment]
Fixed by a4745d8e6dc8a5bb5538692fb9c03fd715102f48 😉

**Comment by Lmmb74** [comment]
:D

**Comment by Lmmb74** [comment]
Would you mind updating to the latest waterfall commit again?
