### ISSUE TITLE
Readd kamico's patch to improve connection closing

### ISSUE THREAD

**Issue by HAMMERxPL** [WaterfallMC/Travertine#25]
Hi, why do you need to delay disconnecting?

>    public void delayedClose(final Runnable runnable)
>     {
>         Preconditions.checkArgument( runnable != null, "runnable" );
> 
>         if ( !closing )
>         {
>             closing = true;
> 
>             // Minecraft client can take some time to switch protocols.
>             // Sending the wrong disconnect packet whilst a protocol switch is in progress will crash it.
>             // Delay 500ms to ensure that the protocol switch (if any) has definitely taken place.
>             ch.eventLoop().schedule( new Runnable()
>             {
> 
>                 @Override
>                 public void run()
>                 {
>                     try
>                     {
>                         runnable.run();
>                     } finally
>                     {
>                         ChannelWrapper.this.close();
>                     }
>                 }
>             }, 500, TimeUnit.MILLISECONDS );
>         }
>     }
>

**Comment by minecrafter** [comment]
This is a Mojang issue.

**Comment by HAMMERxPL** [comment]
@minecrafter What would happen if you delete the delay? You deleted it on Waterfall (old version for sure).

**Comment by Techcable** [comment]
Oh yes, we need to readd @kamcio96 's patch to [improve connection closing](https://github.com/WaterfallMC/Waterfall-Old/commit/b8845c4edbae46bb66f6adda338330a1d4032057).
Thanks for bringing this up. I can't believe I missed that diff when I migrated to the patch-based system.

**Comment by kamcio96** [comment]
I have new idea and will create new patch directly to BungeeCord :wink:

**Comment by Techcable** [comment]
Are you going to try and contribute upstream? Good luck, they don't accept substantial PRs.
