### ISSUE TITLE
Hey, i built Travertine successfully, and i got like 10 jars, what do i do?

### ISSUE THREAD

**Issue by DrPiggy** [WaterfallMC/Travertine#27]
![image](https://cloud.githubusercontent.com/assets/16208640/20669817/ce512daa-b57e-11e6-92dd-65904d5858ea.png)
each of this folders has a jar, which should i use?

P.S. why are the alternative and main ci's of aquifer so i cant just download the jar and have to build this

**Comment by kamcio96** [comment]
bootstrap/target/Travertine.jar

**Comment by Lmmb74** [comment]
Close this, as it was answered
