### ISSUE TITLE
Travertine jar

### ISSUE THREAD

**Issue by DanielAlves123** [WaterfallMC/Travertine#34]
Where can I get Travertine jar?

**Comment by minecrafter** [comment]
https://ci.minimum.io/job/Travertine/

**Comment by kamcio96** [comment]
@minecrafter Can you add this link to project description?

**Comment by minecrafter** [comment]
Later

**Comment by t0rched** [comment]
Travertine didn't actually fix anything for me in 1.7.10. Same crashes as with Waterfall. Random packet crashes etc. What is "Travertine" supposed to do _exactly_?

**Comment by t0rched** [comment]
> Travertine is Waterfall + 1.7 support. If you're having issues with Waterfall, it's unlikely Travertine will help.


I am 100% confused now. I can't run Waterfall on 1.7. That's the reason for Travertine no? Waterfall doesn't support 1.7.10.
