### ISSUE TITLE
Travertine - Netty IO Direct Buffers

### ISSUE THREAD

**Issue by SwissRabbi** [WaterfallMC/Travertine#37]
Logging into my server gives this error - http://pastebin.com/ZBiTCSkt

Operating System: CentOS 6.6 Final
Java: Java(TM) SE Runtime Environment (build 1.8.0_101-b13)

Lobby Version: Spigot 1.11.2
Client Version: 1.11.2
Travertine Version: #4 from https://ci.minimum.io/job/Travertine/

Happy to supply any other info/configs. Thank you.

**Comment by minecrafter** [comment]
Not an issueOn Jan 13, 2017 10:50 PM, SwissRabbi <notifications@github.com> wrote:Logging into my server gives this error - http://pastebin.com/ZBiTCSkt
Operating System: CentOS 6.6 Final
Java: Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Lobby Version: Spigot 1.11.2
Client Version: 1.11.2
Travertine Version: #4 from https://ci.minimum.io/job/Travertine/
Happy to supply any other info/configs. Thank you.

**Comment by SwissRabbi** [comment]
Is there a way to surpress the warning at least make it less intrusive?

**Comment by Techcable** [comment]
It should only occur once, but I guess we can add an option to disable it 😉

**Comment by SwissRabbi** [comment]
I would appreciate that so much! Thank you for your response and time.
