### ISSUE TITLE
Using a io.netty.buffer.PooledUnsafeHeapByteBuf, not a direct byte buf! [1.8 Client]

### ISSUE THREAD

**Issue by Kurimatzu** [WaterfallMC/Travertine#38]
16:29:25 [INFORMAÇÕES] [yKuriDev_|/127.0.0.1:60203] <-> ServerConnector [lobby] has connected
16:29:26 [GRAVE] java.lang.Throwable: Using a io.netty.buffer.PooledUnsafeHeapByteBuf, not a direct byte buf!
16:29:26 [GRAVE]     at net.md_5.bungee.protocol.Varint21FrameDecoder.decode(Varint21FrameDecoder.java:64)
16:29:26 [GRAVE]     at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
16:29:26 [GRAVE]     at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
16:29:26 [GRAVE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
16:29:26 [GRAVE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
16:29:26 [GRAVE]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
16:29:26 [GRAVE]     at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
16:29:26 [GRAVE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
16:29:26 [GRAVE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
16:29:26 [GRAVE]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
16:29:26 [GRAVE]     at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
16:29:26 [GRAVE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
16:29:26 [GRAVE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
16:29:26 [GRAVE]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
16:29:26 [GRAVE]     at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
16:29:26 [GRAVE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
16:29:26 [GRAVE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
16:29:26 [GRAVE]     at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
16:29:26 [GRAVE]     at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
16:29:26 [GRAVE]     at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:651)
16:29:26 [GRAVE]     at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:574)
16:29:26 [GRAVE]     at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:488)
16:29:26 [GRAVE]     at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:450)
16:29:26 [GRAVE]     at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
16:29:26 [GRAVE]     at java.lang.Thread.run(Unknown Source)
>

**Comment by MrPowerGamerBR** [comment]
Duplicate https://github.com/WaterfallMC/Waterfall/issues/74
