### ISSUE TITLE
Update submodules for 1.12

### ISSUE THREAD

**Issue by SupremeMortal** [WaterfallMC/Travertine#48]
I need to 1.7 - 1.12 support still and it hasn't been updated on your Jenkins yet.

**Comment by trebiluk** [comment]
Yes! Forge support and 1.12 for networks using 1.7+ would be great.
Sidenote: Tried Hexacord's update, but no luck.

**Comment by SupremeMortal** [comment]
@trebiluk I built Travertine on my own Jenkins. https://ci.incursio.net/job/Travertine/

**Comment by EXilE-EXistance** [comment]
it seems your custom build doesn't support 1.7.10, have yet to test 1.8-1.10, however 1.11 and 1.12 work fine

**Comment by trebiluk** [comment]
Yes, @EXilE-EXistance and I get Custom Payload error with 1.7.10 Forge 1614 (SpaceAstronomy 1.6.6 FTB pack)

**Comment by SupremeMortal** [comment]
Hmm. I guess it needs to be resolved with a patch.
