### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by RaynLegends** [WaterfallMC/Travertine#49]
Travertine does not compile at the moment:

`Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.0.2:testCompile (default-testCompile) on project travertine-chat: Compilation failure: Compilation failure:
[ERROR] /home/peppe/Build/Travertine/Travertine-Proxy/chat/src/test/java/net/md_5/bungee/api/chat/TranslatableComponentTest.java:[18,23] error: unmappable character for encoding ASCII
[ERROR] 
[ERROR] /home/peppe/Build/Travertine/Travertine-Proxy/chat/src/test/java/net/md_5/bungee/api/chat/TranslatableComponentTest.java:[18,24] error: unmappable character for encoding ASCII
[ERROR] 
[ERROR] /home/peppe/Build/Travertine/Travertine-Proxy/chat/src/test/java/net/md_5/bungee/api/chat/TranslatableComponentTest.java:[18,43] error: unmappable character for encoding ASCII
[ERROR] 
[ERROR] /home/peppe/Build/Travertine/Travertine-Proxy/chat/src/test/java/net/md_5/bungee/api/chat/TranslatableComponentTest.java:[18,44] error: unmappable character for encoding ASCII
[ERROR] 
[ERROR] /home/peppe/Build/Travertine/Travertine-Proxy/chat/src/test/java/net/md_5/bungee/api/chat/TranslatableComponentTest.java:[18,47] error: unmappable character for encoding ASCII
[ERROR] 
[ERROR] /home/peppe/Build/Travertine/Travertine-Proxy/chat/src/test/java/net/md_5/bungee/api/chat/TranslatableComponentTest.java:[18,48] error: unmappable character for encoding ASCII
[ERROR] 
[ERROR] /home/peppe/Build/Travertine/Travertine-Proxy/chat/src/test/java/net/md_5/bungee/api/chat/TranslatableComponentTest.java:[18,65] error: unmappable character for encoding ASCII
[ERROR] 
[ERROR] /home/peppe/Build/Travertine/Travertine-Proxy/chat/src/test/java/net/md_5/bungee/api/chat/TranslatableComponentTest.java:[18,66] error: unmappable character for encoding ASCII
[ERROR] 
[ERROR] /home/peppe/Build/Travertine/Travertine-Proxy/chat/src/test/java/net/md_5/bungee/api/chat/TranslatableComponentTest.java:[39,23] error: unmappable character for encoding ASCII
[ERROR] 
[ERROR] /home/peppe/Build/Travertine/Travertine-Proxy/chat/src/test/java/net/md_5/bungee/api/chat/TranslatableComponentTest.java:[39,24] error: unmappable character for encoding ASCII
[ERROR] 
[ERROR] /home/peppe/Build/Travertine/Travertine-Proxy/chat/src/test/java/net/md_5/bungee/api/chat/TranslatableComponentTest.java:[39,43] error: unmappable character for encoding ASCII
[ERROR] 
[ERROR] /home/peppe/Build/Travertine/Travertine-Proxy/chat/src/test/java/net/md_5/bungee/api/chat/TranslatableComponentTest.java:[39,44] error: unmappable character for encoding ASCII
[ERROR] 
[ERROR] /home/peppe/Build/Travertine/Travertine-Proxy/chat/src/test/java/net/md_5/bungee/api/chat/TranslatableComponentTest.java:[39,47] error: unmappable character for encoding ASCII
[ERROR] 
[ERROR] /home/peppe/Build/Travertine/Travertine-Proxy/chat/src/test/java/net/md_5/bungee/api/chat/TranslatableComponentTest.java:[39,48] error: unmappable character for encoding ASCII
`

**Comment by electronicboy** [comment]
Closing. No idea where this stems from, if this was an issue on the build server it's been long fixed. if it's an issue when you were building yourself, that would be because you're building in an environment without UTF-8 for some reason.
