### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by ridalarry** [WaterfallMC/Travertine#51]
As it says in the readme.md "Additional Client Version Support: Travertine aims to support client versions older then what is supported in upstream. This includes 1.7 support. Additionally Travertine may release Snapshot and PRE Client support patches as time permits." I am wondering if maybe you could use this plugin features, as this plugin is abandoned and no longer works

https://github.com/ProtocolSupport/ProtocolSupportBungee

**Comment by electronicboy** [comment]
Nope, Travertine does not intend to provide any form of translation between protocol versions.
