### ISSUE TITLE
How do I install Travertine?

### ISSUE THREAD

**Issue by Velikss** [WaterfallMC/Travertine#59]
I'm working on setting up a network of modded 1.7.10 KCauldron servers, and Travertine seems really handy to handle it. But how do I install it? There is no .jar downloadable... and windows doesn't seem to run build.sh.

Can anyone help me out here?

**Comment by Capri205** [comment]
There are specific use cases for Waterfall, but on the whole you will get better service using HexagonMC as the dev's here aren't interested in keeping Waterfall going. Your 1.7.10 servers will be unavailable too often using Waterfall.

**Comment by Velikss** [comment]
Thanks, never seen that one! I'll give it a try. 
Im planning on having two servers with both different mods. Because they are using different modpacks I will need an unmodded Spigot hub right? Or is that not needed in HexagonMC?

**Comment by Capri205** [comment]
Waterfall / HexagonMC is just the entry point which let's the client in and directs them accordingly, so it doesn't care what the lobby server is - forge, thermos,, spigot etc. Your lobby/hub however will need to run the appropriate mods or plugins to support the various client versions that people will connect with. I run a spigot 1.12.2 server with ProtocolSupport so clients from 1.7.10 to 1.12.2 can connect.

**Comment by Velikss** [comment]
About that, how do you put a Forge server in a bungeenetwork, the same way you would with a Spigot one?

**Comment by Capri205** [comment]
I run my forge 1.7.10 servers using Thermos-1.7.10-1614. You will need a spigot.yml in the server folder with bungee=true set. Can be a little trial and error to get working, but ping me privately for more help there.  I run 1.10.2 forge servers with forge 1.10.2 and spongeforge-1.10.2 to allow the bungee connectivity.

**Comment by Velikss** [comment]
Yea. The problem with KCauldron/Thermos is that I'm running a LOTR modded server and the LOTR mod doesnt quite like KCauldron... Every LOTR update it breaks and then someone has to come up with some patch and its overal not working very well with LOTR. 

I am planning on switching to KCauldron but there is another LOTR update coming out soon so I'm waiting untill its released and we know for sure it works. Thats why I was interested in wether a normal Forge server would run in a bungee setup, I kinda already knew that it wouldn't work. Do you think there can be a mod that makes it possible?

**Comment by Capri205** [comment]
Ah. yes, it will be hit and miss when trying this integration. I have minor
issue with some mods, like Orespawn, under Thermos. What particularly is
the issue with LOTR? I've never tried that mod so I might give it a try as
we need to retire some of the older servers we've thoroughly beaten.

**Comment by electronicboy** [comment]
Issue trackers aren't forums, if you want a discussion, take it to somewhere suitable, especially if you're going to be using software that has nothing to do with this project.

Waterfall is still maintained, Travertine is a bit slower due to the one or two people who were working on it have left minecraft altogether, as such it's left to contributors to help along.

**Comment by Techcable** [comment]
This one seems to work: https://ci.aquifermc.org/job/Travertine/
