### ISSUE TITLE
Kick when entering portal

### ISSUE THREAD

**Issue by yasha107** [WaterfallMC/Travertine#63]
When I jump in the portal to the Dragon Block server (cauldron) I just get disconnected, in console I get this error: [FlyrkyGameplays] disconnected with: [0;37;1mEncoderException : java.lang.NullPointerException @ io.netty.handler.codec.MessageToByteEncoder:125[39;0m

 In the cauldron console, it appears this: >[12:50:48 INFO]: FlyrkyGameplays lost connection: Internal Exception: java.io.IOException: Broken pipe

**Comment by electronicboy** [comment]
No idea what you mean by "the Dragon Block server", but if you have mods on the server, try replicating your issues with a fresh install without any mods; Shamefully not all mods support having a proxy jammed in the middle

**Comment by yasha107** [comment]
I already have done that, I still get same error, no mods on cauldron, no mods in client

**Comment by yasha107** [comment]
By saying "Dragon block server" I mean my cauldron server that has dragon block mods but I already installed Cauldron from 0 without mods and as I said, I get same error

**Comment by yasha107** [comment]
Can it be because I have via version and via rewind in Travertine plugins?

**Comment by yasha107** [comment]
Closing issue because it was fault of Via Version and Via Rewind being in the plugins folder of Travertine
