### ISSUE TITLE
messages.properties not changing?

### ISSUE THREAD

**Issue by BrettplayMC** [WaterfallMC/Travertine#68]
Currently trying to edit the messages in Travertine like normal bungeecord but it does not seem to be working.  I tried putting my messages.properties into the jar, replacing the old one and putting it in the main bungeecord server directory yet it does not work.  Using latest travertine, here is my file: (renamed to upload to here)
[messages.txt](https://github.com/WaterfallMC/Travertine/files/2020481/messages.txt)

**Comment by electronicboy** [comment]
Try saving your file using unix line endings as opposed to using windows line endings, we've not made any changes around this, and looking at the source, I cannot see how this would fail beyond encoding issues of your messages file
