### ISSUE TITLE
Please remove the outdated build timer

### ISSUE THREAD

**Issue by Tom-III** [WaterfallMC/Travertine#70]
Is there a way to disable it via parameters? "IKnowWhatIAmDoing" ?

**Comment by electronicboy** [comment]
`IReallyKnowWhatIAmDoingISwear`
Upstream merge has just been pushed, activity has been somewhat slow due to other commitments, but I'll try to ensure we don't actually push the timer for people again, if we come close, I'll look into softening the blow.
