### ISSUE TITLE
BungeeCord issue

### ISSUE THREAD

**Issue by Xayanix** [WaterfallMC/Travertine#71]
After receiving this packet: https://hastebin.com/vicamacaza.md

BungeeCord seems like to work pretty slow, joining or pinging server is almost impossible but players which are already connected to server are playing pretty smoothly. BungeeCord is like that till restart. Im using haproxy.

**Comment by Xayanix** [comment]
Im developing every plugin on my bungeecord, im sure its not plugin fault. That thing is pretty strange, because it doesnt affect players online, only new connections and it happens always after this trace xD

**Comment by electronicboy** [comment]
@ThatKawaiiSam that sounds completely unrelated to this issue and should belong in a new issue with log files which provide some information, "Lost connection" is a pretty generic message in which means that the connection between the proxy and the server was killed, generally from the side of the server and not bungee.

Closing this issue, there is nothing that I can see on our side which would cause bungee to be in the completely wrong connection state unless some client isn't handling connections properly. this report indicates that either the connection was opened already in the wrong state, or a client sent the handshake after already putting the connection into the status state.
