### ISSUE TITLE
Players gettings kicked

### ISSUE THREAD

**Issue by cuervito** [WaterfallMC/Travertine#75]
Hello, I need urgent help. I have the latest version of travertine. the problem is when a user enters with version 1.8 forge .. kick all users who have version 1.7 .. giving the following error.

https://pastebin.com/QudVnNFm

**Comment by electronicboy** [comment]
This is not a travertine issue, your server is attempting to send a spawn packet to these players but is then throwing an exception, likely as your server itself isn't capable of handling the protocol changes between 1.7 and 1.8 properly.
