### ISSUE TITLE
Delayed Logins

### ISSUE THREAD

**Issue by kjl13** [WaterfallMC/Travertine#76]
Hello, I started using Travertine today and I noticed it now takes around 7-10 seconds to log in compared to 0-2 when using hexacord.

I'd like to continue to use Travertine to increase performance but I can't if player logins are delayed by around 10 seconds each time.

Thanks for reading, have a great rest of your day.

**Comment by electronicboy** [comment]
Issue was resolved on discord and was down to the async netty dns resolver
