### ISSUE TITLE
unable to build Travertine

### ISSUE THREAD

**Issue by alex450** [WaterfallMC/Travertine#8]
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0

[INFO]
[INFO] --- maven-jar-plugin:2.3.2:jar (default-jar) @ travertine-config ---
[INFO] Building jar: /root/1.7waterfall/Travertine/Travertine-Proxy/config/target/travertine-config-1.10-SNAPSHOT.jar
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Travertine-Event 1.10-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: https://repo.techcable.net/content/groups/public/net/techcable/event4j/1.1.0/event4j-1.1.0.pom
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Travertine-Parent ................................. SUCCESS [0.553s]
[INFO] Travertine-Chat ................................... SUCCESS [1.908s]
[INFO] Travertine-Config ................................. SUCCESS [1.453s]
[INFO] Travertine-Event .................................. FAILURE [0.590s]
[INFO] Travertine-Protocol ............................... SKIPPED
[INFO] Travertine-API .................................... SKIPPED
[INFO] Travertine-Native ................................. SKIPPED
[INFO] Travertine-Query .................................. SKIPPED
[INFO] Travertine-Proxy .................................. SKIPPED
[INFO] Travertine-Bootstrap .............................. SKIPPED
[INFO] Travertine Modules ................................ SKIPPED
[INFO] cmd_alert ......................................... SKIPPED
[INFO] cmd_find .......................................... SKIPPED
[INFO] cmd_list .......................................... SKIPPED
[INFO] cmd_send .......................................... SKIPPED
[INFO] cmd_server ........................................ SKIPPED
[INFO] reconnect_yaml .................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.689s
[INFO] Finished at: Fri Jul 08 12:12:50 CST 2016
[INFO] Final Memory: 48M/2134M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project travertine-event: Could not resolve dependencies for project io.github.waterfallmc:travertine-event:jar:1.10-SNAPSHOT: Failed to collect dependencies for [net.techcable:event4j:jar:1.1.0 (compile), org.ow2.asm:asm-all:jar:5.0.4 (compile), junit:junit:jar:4.12 (test), com.google.guava:guava:jar:18.0 (compile), com.google.code.findbugs:findbugs:jar:3.0.0 (provided), org.projectlombok:lombok:jar:1.14.8 (provided)]: Failed to read artifact descriptor for net.techcable:event4j:jar:1.1.0: Could not transfer artifact net.techcable:event4j:pom:1.1.0 from/to techcable-repo (https://repo.techcable.net/content/groups/public/): peer not authenticated -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :travertine-event

**Comment by TiTo-418** [comment]
https://ci.aquifermc.org/job/Travertine/

**Comment by hunter688** [comment]
Will be posible fix a build? CI is outdated, latest buid is in the august.

repo https://repo.techcable.net/content/groups/public/ is wrong

[ERROR] Failed to execute goal on project travertine-event: Could not resolve dependencies for project io.github.waterfallmc:travertine-event:jar:1.10-SNAPSHOT: Failed to collect dependencies at net.techcable:event4j:jar:1.1.0: Failed to read artifact descriptor for net.techcable:event4j:jar:1.1.0: Could not transfer artifact net.techcable:event4j:pom:1.1.0 from/to techcable-repo (https://repo.techcable.net/content/groups/public/): Received fatal alert: handshake_failure -> [Help 1]
